obj-y				+= rk100_i2c.o

#PWD = $(shell pwd)
#KERNEL_SRC = /home/dell/work/rockchip/3288/firefly-android5.1-180117/kernel/
 
#obj-m := rk100_i2c.o
#module-objs := rk100_i2c.o
 
#all:
#	       $(MAKE) -C $(KERNEL_SRC) M=$(PWD) modules

       
#clean:
#		rm *.ko
#		rm *.o

